name: CI
on: push

jobs:
  ci:
    name: Jest Unit Tests, Type Checking, Linting, Playwright End to End Tests
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    timeout-minutes: 30
    # TODO: Update environment variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: ecommerce_store
      PGUSERNAME: brucem
      PGPASSWORD: Mars.b11
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER $PGUSERNAME PASSWORD '$PGPASSWORD'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=$PGUSERNAME $PGDATABASE
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Jest unit tests
        run: pnpm jest
      - name: Run database migrations
        run: pnpm migrate up
      - name: Build Next.js app (types needed for TSC and ESLint)
        run: pnpm build
      - name: Check TypeScript Types
        run: pnpm tsc

  cd:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: ci
    if: github.ref == 'refs/heads/main'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
